### ISSUE TITLE
Need help with creating configuration file

### ISSUE THREAD

**Issue by kolibrie-eric** [john30/ebusd-configuration#116]
I am attempting to create a definition for a message which has the following characteristics (pbsb + master bytes, leaving out NN=04):

PBSB:  B51A
ID:       05
counter byte: each consecutive message contains count+1 wrt the previous one
SUBID: 321F

The actual data (and type) in the slave bit varies according to the SUBID. Example consecutive telegrams (counter in bold):

7108 _b51a_ 04 _05_ **37** _321f_ e5000a3708 _0500_ 030000000000be00
7108 _b51a_ 04 _05_ **38** _321f_ 37000a3808 _0500_ 030000000000a500

The question is how to make the Ebus daemon skip the counter byte and to make it recognize the data I want. I started with the following configuration:

*r,,,,,,"b51a","05",,,IGN:3,,,
r,,DesiredSupplyTemp,,,,,1f,,,temp,,,,,,IGN:5,,,

This however does not work because I think the daemon does not know how to skip the counter byte in the master part.

Any ideas how to solve this?

Thanks in advance
Eric

**Comment by john30** [comment]
the ID has to be consecutive as of now in the master part, i.e. having a counter in between does not work (yet)

**Comment by kolibrie-eric** [comment]
I figured as much. I created a definition to capture the whole message (master and slave parts) and will do the processing in the receiving code until such a feature might become available. Thx

**Comment by cyberthom42** [comment]
> the ID has to be consecutive as of now in the master part, i.e. having a counter in between does not work (yet)

Is this still the case or does it work now with the current release?

**Comment by cyberthom42** [comment]
Ich habe es hinbekommen:
`# B5 1A Fachhandwerker Konfiguration,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
*r,,,,,,"B51A","05FF34",,,IGN:3,,,,,,,,,,,,,,,,,,,,,
*w,,,,,,"B51A","06FF34",,,,,,,,,,,,,,,,,,,,,,,,
r;w,,Restfoerderhoehe,,,,,1f,,,UIN,,,,,,,,,,,,,,,,,,,,,
`
