### ISSUE TITLE
[main error] invalid configpath without scanconfig (Version 3.2 + RPi3B+)

### ISSUE THREAD

**Issue by szopler** [john30/ebusd-configuration#119]
Hi!
I'm trying to run ebusd on raspberry pi 3B+ but something goes wrong. After successful compilation and installation I tried to execute: 
> ebusd -f –scan-config -d/dev/rfcomm1

but I've got error as in subject. rfcomm1 is an ebus to bluetooth uart adaptor.
Also after:
> ebusd --configpath=http://ebusd.eu/config -f -scan-config -d/dev/rfcomm1

I've got:
> ebusd: invalid initial scan address
> Try `ebusd --help' or `ebusd --usage' for more information.

**Comment by john30** [comment]
you misspelled the scanconfig option, you need to use:
`ebusd -f --scanconfig -d /dev/rfcomm1`
