### ISSUE TITLE
Duplicates in 2.x.x ?

### ISSUE THREAD

**Issue by biohazardxxx** [john30/ebusd-configuration#12]
HI,

first I'm new to ebusd and installed it fresh on raspberry pi after reading documentation.
I've placed ebusd-2.x.x/de folder into /etc/ebusd
When I run ebusd --scanconfig I get a lot duplicate errors. Please see attached file for full output.
Am I doing something wrong?

Regards
Bio
[ebusd_conf_check.txt](https://github.com/john30/ebusd-configuration/files/88097/ebusd_conf_check.txt)

**Comment by john30** [comment]
please post the complete command line used when starting ebusd to check the config.
John

**Comment by john30** [comment]
From your log file, it seems you didn't add "--scanconfig" to your ebusd command line. If you do so, the duplication warnings should vanish.
Furthermore, the download of the CSVs didn' work well, as symbolic links were converted to files containing the name of the linked file (e.g. "/etc/ebusd/vaillant/05.vd6.csv").
Please follow the instructions noted here: https://github.com/john30/ebusd-configuration/releases/latest
