### ISSUE TITLE
Chained messages and duplicate entrys

### ISSUE THREAD

**Issue by rellla** [john30/ebusd-configuration#122]
Hi,
i'm trying to figure out, how to deal with the time scheduling messages and to find out, what's the best way to integrate them in fhem.

To get the schedule of a week, i have to chain the following messages to "timeprogramm" beginning with "tp1". Every byte of the answer matches the duration of 2 hours, where 1 bit matches 15 minutes. 
"tp1" for example consists of 10 bytes. So i will get 20hours (=10bytes) of monday and need the first 2bytes (=4hours) of "tp2" to complete the monday. 
I can successfully chain all together to a complete week. Now i tried to use chained messages which will allow me to read a special day, see "tp_monday" and "tp_tuesday". This works so far but as soon as i define 2 chained messages (e.g tp_monday and tp_tuesday), ebusd gives me a duplicated entry(duplicate ID) error...

I wonder if this is an issue and if not, can you tell me the place in the code, where i may implement that?
Otherwise i think i have to solve that in fhem...
```
*r,ww_timeprogramm,,,,15,0622,05,,,,,,,,,,,,,,,,,,,,,,,,
r,,tp0,Zeitprogramm Warmwasser Teil 1,,,,bd004e,prefix,,tp_status,,,,,,,,,,,,,,,,,,,,,
r,,tp1,Zeitprogramm Warmwasser Teil 2,,,,bd014e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp2,Zeitprogramm Warmwasser Teil 3,,,,bd024e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp3,Zeitprogramm Warmwasser Teil 4,,,,bd034e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp4,Zeitprogramm Warmwasser Teil 5,,,,bd044e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp5,Zeitprogramm Warmwasser Teil 6,,,,bd054e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp6,Zeitprogramm Warmwasser Teil 7,,,,bd064e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp7,Zeitprogramm Warmwasser Teil 8,,,,bd074e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp8,Zeitprogramm Warmwasser Teil 9,,,,bd084e,schedule,,tp_20h,,,,,,,,,,,,,,,,,,,,,
r,,tp9,Zeitprogramm Warmwasser Teil 10,,,,bd094e,schedule,,tp_8h,,,,,,,,,,,,,,,,,,,,,
#r,,timeprogramm,Zeitprogramm Warmwasser,,,,bd014e;bd024e;bd034e;bd044e;bd054e;bd064e;bd074e;bd084e;bd094e,all,,tp_week,,,,,,,,,,,,,,,,,,,,,
r,,tp_monday,Zeitprogramm Warmwasser Montag,,,,bd014e;bd024e,monday,,tp_24h,,,,unneeded,,tp_16h,,,,,,,,,,,,,,,
r,,tp_tuesday,Zeitprogramm Warmwasser Dienstag,,,,bd024e;bd034e,unneeded,,tp_4h,,,,tuesday,,tp_24h,,,,unneeded,,tp_12h,,,,,,,,,
```
Thanks
rellla

**Comment by john30** [comment]
can't be done day by day then, just define one chained message with all days in it
