### ISSUE TITLE
Make message definitions language independent

### ISSUE THREAD

**Issue by andr2000** [john30/ebusd-configuration#126]
While working on adding new commands one needs to add the same for en and de folders which only differ in languages used. It can probably be solved by moving language specific strings to dedicated files and inc files just reference some ID of the corresponding strings.
This way we only have a single definition of a command (which is good) and still have a possibility for message localization.

**Comment by andig** [comment]
John mentioned he is already working on v3 configs which will have languages in a single file

**Comment by andr2000** [comment]
Missed that, sorry for the buzz
