### ISSUE TITLE
Replace r9 with r in yield4445.inc for YieldThisYear

### ISSUE THREAD

**Issue by Tranquility76** [john30/ebusd-configuration#127]
Hi John,

why is YieldThisYear set to r9? This value only changes infrequently but having r9 gives a lot of entries in the ebusd.log. (Which causes unnecessary writes on the SDCard.)

Thanks
Sebastian

**Comment by john30** [comment]
9 is like the factor to be applied on the polltimeout, so having 9 there will lead to these messages polled as rare as possible

**Comment by Tranquility76** [comment]
Hi,

I know (from the Wiki) that 9 means least poll intervall?

The question was, why this field is marked for automatic poll at all. It only changes once a day so automatic poll makes no sense from my point of view.

And the poll happens very often according to my logs. (a few times per minute if I remember right)

Am 04.01.2019 um 17:16 schrieb John <notifications@github.com<mailto:notifications@github.com>>:


9 is like the factor to be applied on the polltimeout, so having 9 there will lead to these messages polled as rare as possible

**Comment by john30** [comment]
in order to have the yield available on a regular basis.
you can just increase the poll timeout or disable polling by setting it to 0
