### ISSUE TITLE
VR 39: Add definition

### ISSUE THREAD

**Issue by rousseldenis** [john30/ebusd-configuration#193]
Hi all,

I try to add my VR39 (coupler between old burners and eBus).

It is found. ebusctl info:

address 08: slave #11, scanned "MF=Vaillant;ID=V3x00;SW=0118;HW=9902", loaded "vaillant/08.v3x00.csv"

I first set a fake file with an icovit burner to check if it finds it.

What is the best method to populate csv ?

Thanks for your advices.

**Comment by john30** [comment]
start a pull request with english and german version of the file

**Comment by john30** [comment]
closed as further discussed in #226
