### ISSUE TITLE
Add VRC 720f / basv0 config to online config source

### ISSUE THREAD

**Issue by xxxturboxxx** [john30/ebusd-configuration#200]
Im using the Vaillant VRC 720 f which I the wireless version of the VRC 720. As mentioned before in some other posts the VRC 720 config is working 100% fine with the 15.700.csv. 
In my case the 15.700.csv works also 100% after renaming it to 15.basv0.csv due to the fact that the receiver is connected to the ebus and not the VRC 720 f itself.

At the moment I'm using locally saved csv's but it would be nice to be able to switch to the online ones in order to get possible updates automatically

Please can you add the 15.basv0.csv (renamed 15.700.csv) to the online database?

Thanks!

**Comment by john30** [comment]
noch ein issue?
Duplikat von #196
