### ISSUE TITLE
Plz help with the adjustment of srew 8 of the ebus couper from e-service online

### ISSUE THREAD

**Issue by Gil76** [john30/ebusd-configuration#21]
I have read a lot about the adjustment of the trimmer for the signal but i dit not yet succeed for making the correct adjustment. What's the best way to check that the trimmer from de hardware adapter is in the correct position. It is for the e-bus coupler with an USB connection and i have a raspberry pi OR windows 10 pc available for checking the device.

**Comment by john30** [comment]
you should enable raw logging in ebusd and then do the following:
1. turn the pot to the leftmost position
2. turn it to the right until the led starts blinking
3. slowly turn it to the left again until you see a lot of "< aa" messages in the ebusd log
