### ISSUE TITLE
ebusd-configuration-2.1.b143f39-en_all.deb is not an archive in debian-format

### ISSUE THREAD

**Issue by Gil76** [john30/ebusd-configuration#22]
Hello,
By running this command  sudo dpkg -i --force-overwrite ebusd-configuration-2.1.*.deb my RPi gives an error that the archive is not in debian-format ?

# In Dutch : 
dpkg-deb: fout: `ebusd-configuration-2.1.b143f39-en_all.deb' is geen archief in debian-formaat
dpkg: fout bij verwerken van archief ebusd-configuration-2.1.b143f39-en_all.deb (--install):
 subproces dpkg-deb --control gaf een foutwaarde 2 terug
Fouten gevonden tijdens verwerken van:
 ebusd-configuration-2.1.b143f39-en_all.deb

Anny idea of the problem ?

**Comment by john30** [comment]
You probably did a mistak when transferring the file to your RPi.
Best is to download it directly with the following command on the RPi:
`wget https://github.com/john30/ebusd-configuration/releases/download/v2.1.1/ebusd-configuration-2.1.b143f39-en_all.deb`
