### ISSUE TITLE
readallvaillantregisters.sh

### ISSUE THREAD

**Issue by grossfr** [john30/ebusd-configuration#230]
@john30
bei der Verwendung von https://github.com/john30/ebusd/blob/master/contrib/scripts/readallvaillantregisters.sh besteht hier nicht die Möglichkeit, dass ungewollte Schaltbefehle oder Sollwerte gesendet werden?
Gibt es eine Möglichkeit alle Register nur zu lesen ohne zu schreiben?

**Comment by LukasGrebe** [comment]
mit dem `-r, --readonly` Flag beim start des ebusd sollte das verhindert werden können. Siehe auch: Only read from device, never write to ithttps://github.com/john30/ebusd/wiki/2.-Run#device-options

**Comment by john30** [comment]
warum macht man mehrere [Einträge](https://github.com/john30/ebusd-configuration/issues/72#issuecomment-921949359) für den selben Inhalt? Das kostet jeden der es liest unnötig Zeit. Verstehe ich nicht.
