### ISSUE TITLE
In 2.1 config files please correct 15.470.csv 

### ISSUE THREAD

**Issue by texel007** [john30/ebusd-configuration#24]
[SW>=202]r;w,,InternalOperatingMode470,InternalOperatingMode470,,,,"3100",,,UCH,2=auto;3=on;4=night;5=summer,,"operation mode of the second heating circuit for 470 (2 = auto, 3 = on, 4 = night, 5 = summer)"

(added modes in clear text)

**Comment by john30** [comment]
are you sure about this? according to my information, 3100 is the heating curve...

**Comment by john30** [comment]
closed due to inactivity
