### ISSUE TITLE
¿I can force load file to address?

### ISSUE THREAD

**Issue by edudele** [john30/ebusd-configuration#271]
After time fiddling with files and the daemon.
I would like to know if it is possible to force the loading of a file in one direction. for instance:

> address 15: slave #2, scanned "MF=Vaillant;ID=BASV0;SW=0217;HW=8803"

I would like to force the loading of the 17.500.csv file since it does not take it by itself.

**Comment by john30** [comment]
please avoid useless duplication, answered [here](https://github.com/john30/ebusd/discussions/654#discussioncomment-3784941)
