### ISSUE TITLE
SingleStorageCharge incorrect response

### ISSUE THREAD

**Issue by Tranquility76** [john30/ebusd-configuration#33]
Using the 0a.pmw.hwc.csv (VPM-W Fresh Water Station) I get for

r -c hwc SingleStorageCharge
Off

while currently SingleStorageCharge is running so response should be ON.

SingleStorageCharge can also be triggered by the VRS 620/3 but currently SingleStorageCharge is a read only value.

Would be nice if we could figure out the correct values for reading / writing SingleStorageCharge as I need this to workaround an issue in the Vaillant Firmware.

**Comment by john30** [comment]
did you check without using the cache? i.e.
`r -f -c hwc SingleStorageCharge`

**Comment by Tranquility76** [comment]
yes, I did -same result "off"

**Comment by john30** [comment]
I guess the quick command "load" should also work on the HWC unit. So try adding the following line:
`!include,quick.inc,,,,,,,,,,,,`
to the 0a.pmw.hwc.csv, then issue a readod (or restart ebusd), then "ebusctl w -c hwc load", and after that check the SingleStorageCharge value again.

**Comment by Tranquility76** [comment]
Hi John,

I tried w -c hwc load after the include and got
ERR: invalid numeric Argument

:-(

If I remember right I tried this already a few weeks ago...

**Comment by john30** [comment]
sorry, you need to send "`ebusctl w -c hwc load on`"

**Comment by Tranquility76** [comment]
:-(

ebusctl w -c hwc load on
done

ebusctl r -c hwc SingleStorageCharge
off

I am not at home so I cannot check at the VRS Display if the SingleStorageCharge was started but not reflected in the hwc query.

**Comment by Tranquility76** [comment]
temperature is increasing - seems the write command was working only the read command queries the wrong Thing...

**Comment by john30** [comment]
you need to avoid using the cached data with the "-f" option to the read command. Furthermore, the device might need a few seconds (or even a minute) until it reflects the request in the data.

**Comment by Tranquility76** [comment]
Hi John,

now have the time to directly test at the device.

ebusctl w -c hwc load on
done
--> nothing happens at the VRS/Heater/...

Turned on SingleStorageCharge directly at the VRS --> Heater started to charge hot water area of the storage.

Waited a few minutes... (still charging)

ebusctl r -c hwc -f SingleStorageCharge
off

So it seems both commands do not work... :-(

Tested 
ebusctl w -c hwc load off
done
--> nothing happens, still charging...

**Comment by john30** [comment]
well, you never know how that message is interpreted.
so it seems that the SingleStorageCharge is not related to the "load" instruction.

**Comment by Tranquility76** [comment]
Do you know with whitch hardware SingleStorageCharge is working? Maybe I can try to compare a little bit...

**Comment by john30** [comment]
no I don't, I never use that feature.
