### ISSUE TITLE
Wieso jedesmal scanconfig?

### ISSUE THREAD

**Issue by peterfido** [john30/ebusd-configuration#336]
Hi, wäre es nicht von Vorteil, wenn einmal gefundene Geräte über einen Neustart hinaus gemerkt werden würden? So oft ändert sich eine Heizungsanlage nicht. 

Aktuell braucht es nach einem Neustart wieder einige Zeit, bis alle nötigen csv und inc Dateien geladen wurden.

**Comment by smartboart** [comment]
Gute Frage.

**Comment by obduser** [comment]
Nächste - kommt eh nix

**Comment by john30** [comment]
duplicate of https://github.com/john30/ebusd/issues/927
