### ISSUE TITLE
Multiple commandline_options not working in add-on

### ISSUE THREAD

**Issue by stingone** [john30/ebusd-configuration#339]
How can multiple commandline_options work in the hass add-on. The /etc/ebusd folder i cannot find as it is running in a docker container. when change to my local /config/ folder the config file is not loading therefore injecting is only working for me at the moment.

however only one commandline_option is working in the yaml not multiple.

i want both the --mqttvar=filter-direction=r|u|^w and --mqttvar=filter-name=

**Comment by john30** [comment]
obviously the wrong repo. ask in the hassio add-on repo
