### ISSUE TITLE
unable to load scan config 15

### ISSUE THREAD

**Issue by Benni1123** [john30/ebusd-configuration#358]
Hi @john30 
I have this issue.
`2023-10-08 18:47:49.170 [update notice] sent scan-read scan.15 id QQ=31: 21;22;32;0010045485;0953;011543;N1
2023-10-08 18:47:49.170 [bus notice] scan 15: ;21;22;32;0010045485;0953;011543;N1
2023-10-08 18:47:49.295 [main error] unable to load scan config 15: no file from vaillant with prefix 15 matches ID "ctlv3", SW0612, HW3004
2023-10-08 18:47:49.295 [main error] scan config 15: ERR: element not found`

ebusctl find output:
`scan.08  = Vaillant;BAI00;0807;7603
scan.08 id = 21;22;44;0010022010;0001;017235;N0
scan.15  = Vaillant;CTLV3;0612;3004
scan.15 id = 21;22;32;0010045485;0953;011543;N1`

Can you please help me, so that I can use my heating?

**Comment by john30** [comment]
then there is no such file yet in the repo (15.ctlv3.csv) and you'd have to create that yourself. you could look for another ctlv* and see if that works

**Comment by john30** [comment]
[#487 ](https://github.com/john30/ebusd/issues/487) might be related

**Comment by Benni1123** [comment]
> [#487 ](https://github.com/john30/ebusd/issues/487) might be related
![image](https://github.com/john30/ebusd-configuration/assets/37271495/c9044184-8da4-4550-93f3-9433012f486e)

it looks not bad.

![image](https://github.com/john30/ebusd-configuration/assets/37271495/e4d84416-4ac1-4e34-a2cd-06eb683c245c)
but unfortunately most of it doesn't work.

**Comment by cjoe-51** [comment]
Linking 15.ctlv2.csv to 15.ctlv3.csv made the ebusd loading the config file finally and 279 of new variables appeared however **all** with result " **no data stored**" :(
What did I made wrong?

scan.15  = Vaillant;CTLV3;0709;3704
scan.15 id = 21;23;34;0020260919;0953;007103;N6

**Comment by john30** [comment]
done with dec8be9e12b8a85d04cd2db9b41e5e0633d84969
