### ISSUE TITLE
Please add SetModeOverride to Vaillant bai configuration files.

### ISSUE THREAD

**Issue by HiQual** [john30/ebusd-configuration#361]
Please add the following line to bai.308523.inc

wi,BAI,SetModeOverride,Setmode,,08,B510,00,hcmode,,UCH,,,,flowtempdesired,,D1C,,,,hwctempdesired,,D1C,,,,hwcflowtempdesired,,UCH,,,,setmode1,,UCH,,,,disablehc,,BI0,,,,disablehwctapping,,BI1,,,,disablehwcload,,BI2,,,,setmode2,,UCH,,,,remoteControlHcPump,,BI0,,,,releaseBackup,,BI1,,,,releaseCooling,,BI2

Many thanks.

**Comment by john30** [comment]
reworked and merged #388 and #389 in ba4c7491
