### ISSUE TITLE
ERR: invalid position in decode

### ISSUE THREAD

**Issue by k-fil** [john30/ebusd-configuration#371]
Why can't I read energy consumption on my Vaillant 20CS? I'm gettin following error:
![image](https://github.com/john30/ebusd-configuration/assets/22186697/abb682de-12a5-44c9-ae94-351ff45a8ebf)

**Comment by john30** [comment]
looking at the binary answer (as in hex read or find with hex) you should see that the addressed device just didn' answer to the query with reasonable values

**Comment by k-fil** [comment]
So how to change the query? is it possible or isn't for this device?
