### ISSUE TITLE
After new release 08.hmu.csv, strange behavior heat pump Vaillant

### ISSUE THREAD

**Issue by mthomalla** [john30/ebusd-configuration#405]
Hy,
after a new system start of Homeassistant at the 13th of February i noticed that my Vaillant VWL 75/5AS Heatpump suddenly had very short cycles and also very short operation. 
I checked the Ebusd-configuration and saw that there was a new release of the 08.hmu.csv. 
I then stopped the Homeassistant Integration Ebusd. The behavior of the Heatpump went to normal. 

Has anyone else had this experience, or does anyone know what's happening here? 
Before the release of new 08.hmu.csv, Ebusd ran without this behavior of the Heatpump since july 2023.
Since the first installation of the Ebus-Adapter and the Homeassistant Integration Ebusd, i did not made any changes at the Adapter or configuration

Heatpump informations:
Heatpump: Vaillant Arotherm VWL 75/5AS Split, Vaillant Hydraulikstation VWL 77/5IS, Vaillant Controller VRC700

System informations:
Intel NUC i7, Homeassistant Supervisor , Supervisor 2024.02.1, Core 2024.2.3, 
Ebusd-Addon 23.2 (23.3 is on HA not available yet),
Ebusd-Adapter V5 (build 20240106).

Link to the latest csv:
[ebusd-2.1.x/de/vaillant/08.hmu.csv](url)

Link to the adapter i use:
[https://adapter.ebusd.eu/v5/](url) 

I only read the Ebus, never active write to it. 
Logging all sensors works great, the issue is the behavior of the heatpump as you can see in the screenshot, i.e between 19.00 and 20.30.

![Screenshot_20240301_074437_Home Assistant](https://github.com/john30/ebusd-configuration/assets/123564658/2fc70715-b3e4-48d7-ac7a-9da8a416a44f)

The configuration and the log when starting the ebusd addon is:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
ebusd --foreground --mqtthost=core-mosquitto --mqttport=1883 --mqttuser=addons --mqttpass=*************** --scanconfig --mqttjson --latency=10 --accesslevel="*" --pollinterval=5 --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqtttopic=Vaillant --device=ens:192.168.2.155:9999 --log=all:notice --log=main:notice --log=bus:notice
2024-03-01 07:51:04.592 [main notice] ebusd 23.2.p20230716 started with auto scan on device: 192.168.2.155:9999, enhanced
2024-03-01 07:51:05.172 [bus notice] device status: resetting
2024-03-01 07:51:05.173 [bus notice] bus started with own address 31/36
2024-03-01 07:51:05.194 [bus notice] signal acquired
2024-03-01 07:51:05.249 [mqtt notice] connection established`

The log was just for this post. 
The Homeassistant Integration Ebusd remains stopped, the Adapter is still online and connected to the Ebus.
I assume that the behavior of the Heatpump it relates purely to the new 08.hmu.csv.

THX a lot for this amazing project!

**Comment by JonesGW-MGD** [comment]
Hi there, you may wish to join the discussion at https://github.com/john30/ebusd/issues/1205 and https://github.com/john30/ebusd/discussions/1203 if you determine they are the same symptoms (which they appear to be), you may wish to join in with your particular configuration, what has changed recently etc.  What steps you've taken

**Comment by mthomalla** [comment]
I updated the first post. Thanks fpr the mention. Now i know, that there are more user with almost same issue.

**Comment by john30** [comment]
see https://github.com/john30/ebusd/issues/1205#issuecomment-1973714243

**Comment by mthomalla** [comment]
Hello John, 
after reading your comment, I set the Ebusd integration to autostart and completely restarted Homeassistant. The reverted 08.hmu.csv was loaded automatically, as well as other csv for my system. The corresponding data is received correctly. 

The heat pump has been working absolutely normally since then!

If the developers require further data from and for my Vaillant Arotherm Split system, I am ready to support them.
Thank you very much for this great project.
Best regards Marko

**Comment by jkunczik** [comment]
An update from john30/ebusd/issues/1205: We found the culprit. All Home Assistant integrations (MQTT and ebusdpy) actively poll read values. Either the HMU or the controller doesn't take kindly if one of the introduced read values in the updated 08.hmu.csv (we still don't know which) is actively polled by another master, which then leads to a full stop of the heat pump. An issue was opened at ebuspy CrazYoshi/ebusdpy/#10 (for the core integration) and a pull request was opened john30/ebusd#1213 to prevent MQTT from actively polling.

**Comment by mthomalla** [comment]
Thanks for the information. Thank you that there are users who really delve deeply into a topic like this.
