### ISSUE TITLE
_template.csv: double entry 0xee in opdataheat

### ISSUE THREAD

**Issue by J0EK3R** [john30/ebusd-configuration#47]
Hello,
there is a double definition for value 0xee in ebusd-2.1.x _template.csv for type opdataheat.

[https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/de/_templates.csv](url)

0x00=off;
0x01=none;
0x55=hotwater;
0xaa=heating;
0xcc=emissioncheck;
0xdd=qualitycontrol;
**0xee**=controlstop;
0x66=hotwaterincontrolstop;
0xbb=hotwaterinheating;
**0xee**=controlstopinstage

**Comment by john30** [comment]
fixed
