### ISSUE TITLE
Help understanding configuration files

### ISSUE THREAD

**Issue by dkuschmierz** [john30/ebusd-configuration#81]
Hi,
can you please help me understanding your configuration files with an example from me.
I've the following message from my Vaillant VWL ebus (gathered with openhab ebus binding):

QQ: 10
ZZ: 08
PBSB: B509
Remaining: 29 BA 00 51 00 03 BA 00 06 C1 00

I tried to decrypt the data with the 08.ehp.csv

And here i've a little understanding problem.

In the first rows there is PBSB B509 and ID 29, ok that looks ok so far.

A few lines later i see BA00, but it's also in the ID field and not, as i expected, in field one.

I asume that the message gives me the ActualEnvironmentPower, but i've no glue how to decrypt the data. According to the template.csv this should be an unsigned integer.

Can you please help me how to decode this message?

**Comment by john30** [comment]
the line to decode it is actually already there in 08.ehp.csv line 84.
a little backgroun info: the ID column in the CSV defines additional bytes taken in sequence from the master DD in order to extend the message identification formed of ZZ,PBSB and ID.
